### ISSUE TITLE
What happens if *.foo.com and bar.foo.com configure differing endpoints?

### ISSUE THREAD

**Issue by juliatuttle** [WICG/reporting#24]
The spec does not exclude or deprioritize the superdomain (foo.com)'s endpoints, so reports can arbitrarily go to the superdomain or subdomain's endpoints.

My personal instinct is that if the subdomain has configured any endpoints, the UA should assume the subdomain wants to use those instead of the superdomain's endpoints, and send reports for the subdomain exclusively to the endpoints specifically configured by the subdomain, even if they're failing.

Other options include the current behavior (don't care) or prioritizing the subdomain's endpoints but using the superdomain's if the subdomain's are all failing.

**Comment by patrickkettner** [comment]
My vote would be for just sending reports to multiple endpoints (if both domains specify different endpoints, send report to both) rather than one taking over from another. If that had to be the case, the most reports should go to the most specific subdomain.

@RByers @mikewest @igrigorik, thoughts?

**Comment by igrigorik** [comment]
Don't we already solve this in HSTS? I suggest we borrow the logic from there.

> My vote would be for just sending reports to multiple endpoints 

If I'm using subdomains to isolate content under different origins.. that would leak reports across origins, which seems bad.

**Comment by patrickkettner** [comment]
> Don't we already solve this in HSTS? I suggest we borrow the logic from there.

:+1:

**Comment by juliatuttle** [comment]
HSTS checks both, but it seems like the order doesn't matter -- if both *.foo.com and bar.foo.com are present, then HSTS is **definitely** enabled, but it doesn't matter **which** entry counts as having enabled it. With Reporting, it does matter, since we have to choose endpoints.

**Comment by juliatuttle** [comment]
I'm currently implementing this in Chromium such that the most specific domain wins, and overrides the less specific ones even if all of the more specific ones are failing.

**Comment by patrickkettner** [comment]
@RByers does @juliatuttle's [update](https://github.com/WICG/reporting/issues/24#issuecomment-296684036) need to be codified in the spec somewhere? I'm fine with this behavior, just trying to clear out issues when possible

**Comment by dcreager** [comment]
The latest text in the [Send reports](https://wicg.github.io/reporting/#send-reports) section clarifies that most specific domain wins.  (And by extension, that means any `include_subdomains=false` match must be highest priority, since it will only match the most specific possible domain.)
