### ISSUE TITLE
feedback on report failure?

### ISSUE THREAD

**Issue by patrickkettner** [WICG/reporting#30]
In discussion with @travisleithead, and he brought up the fact that while it is great that there is no guarentee that tests be delivered it would be useful to provide some kind of feedback for these failures. If it is failing because tests just can't be sent to that endpoint because of typos or what have you, should we expect the useragent to give some kind of indication in the developer tooling that shows that tests have failed?

**Comment by juliatuttle** [comment]
I'd be okay with this, but is it in line with other specs? Things like CSP don't mandate any local feedback when report uploads fail, do they? If they don't, I think it would make sense to offer it as a suggestion to browser developers (and I'd happily try to do it in Chromium).

**Comment by igrigorik** [comment]
> If it is failing because tests just can't be sent to that endpoint because of typos or what have you, should we expect the useragent to give some kind of indication in the developer tooling that shows that tests have failed?

If you have devtools open and report fails, I'd expect the request to be visible in devtools, plus the return code? If it fails, you'd see it. That should take care of the typo case, right? Personally, I don't think we need to go beyond that.

**Comment by patrickkettner** [comment]
@juliatuttle I am not aware of any other spec mentioning this

I don't believe we should mandate a required set of actions necessarily. A suggestion that the user agent communicate some kind of error, or possibly have a report type that will send a report to an endpoint if one (of a set) is not working (or a more generic "network error" report possibly?).

This was more of a "UAs `Should`, not `Must`" sort of a thing

**Comment by igrigorik** [comment]
> I don't believe we should mandate a required set of actions necessarily. A suggestion that the user agent communicate some kind of error, or possibly have a report type that will send a report to an endpoint if one (of a set) is not working (or a more generic "network error" report possibly?).

"Mandate" and "suggestion" contradict.. :-)

Personally, I don't think issuing error reports on errors of errors reports.. is something we need to do, especially if this is all best effort to begin with. That said, if others think otherwise...

**Comment by patrickkettner** [comment]
> "Mandate" and "suggestion" contradict.. :-)

totally! thats why mandate was preceded with a "dont".

im fine either way, just wanted to bring it up

**Comment by juliatuttle** [comment]
I don't want to build something that reports failed reports specifically (too easy to end up with an infinite loop of reports), but I think if any other spec (e.g. Network Error Logging) happens to make a report based on a failed delivery attempt, that should itself be fair game to deliver.

**Comment by juliatuttle** [comment]
And, yeah, if it's visible in devtools, that should be plenty. Forget I considered plumbing it to the console.

**Comment by patrickkettner** [comment]
:+1:
