### ISSUE TITLE
gh-pages copy not auto-updating

### ISSUE THREAD

**Issue by RByers** [WICG/reporting#31]
There are commits in `master` (such as updating the `report an issue` link) which aren't currently reflected in gh-pages - so the [published spec](http://wicg.github.io/reporting/) is stale.  It looks (from recent PRs) like the Travis job isn't working?

**Comment by RByers** [comment]
Once this is fixed, we should move the couple issues mistakenly filed at https://github.com/w3c/reporting/issues/ over to this repo.

**Comment by igrigorik** [comment]
@plehegar set this up for us originally when we were on w3c/.. Guessing, this broke when we moved to WICG org.

**Comment by plehegar** [comment]
CGs can't publish in /TR. The WebPerf Group should instead republish the TR document as a Working Group Note pointing to the GitHub repo. ok to do that?

**Comment by plehegar** [comment]
(note that we do have a Note there now but it still contains the old content. The new Note would be pretty empty except for pointing to WICG/reporting)

**Comment by RByers** [comment]
I was more worried about the wicg.github.io page myself than the /TR one.  I think that's just a matter of getting bikeshed to run.  Is it still desirable to keep the `master` and `gh-pages` branches separate, or would it be simpler to just push `master` into `gh-pages` (like other WICG repos) and have the Travis job just run bikeshed and commit the result to `gh-pages`?

**Comment by plehegar** [comment]
I suggest matching what the other WICG repos are doing it. This seems simpler to do and easier to maintain in the long run.

**Comment by RByers** [comment]
Although the Travis job was passing, the deploy was still failing for auth reasons.  I've [found updated instructions for setting this up](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) more securely than the version we seem to have in our repo.  We probably want to migrate to that method.

**Comment by RByers** [comment]
Of course I don't have admin access to the repo in order to add a new deploy key.  This hardly seems worth the effort, how about we just rely on people editing the spec to submit the bikeshed output along with their change, then we can remove the Travis job entirely.  That's what, for example, [Feature Policy](https://github.com/WICG/feature-policy) is doing.  @patrickkettner @igrigorik @mikewest any objections?

**Comment by patrickkettner** [comment]
@RByers I asked @plehegar to update the keys and he went and redid the deploy script for us. Should no longer be an issue, correct?

**Comment by plehegar** [comment]
Make sure that the next update will go smoothly before closing this issue. I didn't test it live.

**Comment by RByers** [comment]
Thanks for doing this @plehegar! 

It was still [failing with authentication issues](https://travis-ci.org/WICG/reporting/builds/237290090) because Travis was still configured to run the old deploy script.  I've [removed the old one and updated the travis config](69401dd8b9d5f75fcb16124f406c7cc64575ae04).  We'll see if it works now.

**Comment by RByers** [comment]
I [fixed a little bug in the deploy script](https://github.com/WICG/reporting/commit/03db3d05a430c138d6b0cd0e38803240b20ee4d6) and have  [verified](https://travis-ci.org/WICG/reporting/builds/237307603) that it works correctly (and [correctly skips deployment](https://travis-ci.org/WICG/reporting/builds/237306234) for no-op changes).

I've also [removed](https://github.com/WICG/reporting/commit/c45f5ddc35ba008156f9f912cb0a0221661ab5c6) the stale build output in master.  The only place we have build output now is gh-pages.

Note that Travis apparently now has [built-in gh-pages deployment support](https://docs.travis-ci.com/user/deployment/pages/) which would be much simpler, except that it suffers from the same problem our old script did - potentially exposing someone's personal GitHub access token to all repo collaborators (instead of just a key specific to this repo).  So I'm happy just sticking with the more complex system we have here now that it's working.
