### ISSUE TITLE
Default value for max-age?

### ISSUE THREAD

**Issue by RByers** [WICG/reporting#32]
Is there a benefit to having `max-age` be required?  It seems likely that people often won't understand the implications, and so perhaps we're better off choosing a reasonable default value ourself for when it's not specified (which we could potentially change later if we decided there was a better default)?

**Comment by juliatuttle** [comment]
I'd be okay with this. I'd think a day or a few days would make sense, to try to catch some of the "this site is broken on this network" kinds of errors without keeping these around forever.

**Comment by igrigorik** [comment]
> It seems likely that people often won't understand the implications,

Curious, what makes you think that? It's just like Cache-Control max-age, which is pretty straight forward and well understood?

**Comment by RByers** [comment]
> Curious, what makes you think that? It's just like Cache-Control max-age, which is pretty straight forward and well understood?

Just writing the explainer I realized it wasn't at all obvious to me what I'd pick for `max-age` if I was using this API on some simple site.  In my thinking so far about the reporting API, I had been ignorant of caching implications (which you could argue is a real problem, but still probably one that would be common).  `Cache-Control` itself is optional and only used once you're thinking about how your site should interact with caches, right?  I imagine most people using the Reporting API will not already be thinking about the interaction with caches, so requiring `max-age` feels to me kinda like saying `Cache-Control` is a required header and a response will be ignored with out it.  But you're the expert here - I defer to your judgement (just trying to provide the perspective of a naive web developer).

**Comment by igrigorik** [comment]
Hmm, I think we have some confusion here.. 

max-age is not for the reports; max-age is for how long the advertised endpoint should be remembered by the user agent (similar [to HSTS](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet#Examples)).

**Comment by RByers** [comment]
How exactly is that observably different from indicating the time-out for the report (how I summarized it [here](https://github.com/WICG/reporting/blob/master/EXPLAINER.md#enabling-reporting))?  I guess setting a different max-age in a new request can cause previously generated reports to time out sooner (but that's a pretty subtle difference IMHO).  I.e. endpoints are remembered only for the purpose of sending previously queued reports, right?

**Comment by igrigorik** [comment]
> max-age (required) specifies the maximum time (in seconds) to attempt to deliver a report.

That's not how I originally intended to define it, which explains our confusion.. :-) In my head:
- `max-age`specifies the lifetime of the reporting endpoint
   - "remember this endpoint for the next X seconds"
   - "remember this endpoint for 0 seconds" == unregister this endpoint
   - you can specify multiple endpoints for same report type with different max-age lifetimes
- All of the above is _completely_ separate from the lifetime of the report, which is both best-effort and at the discretion of the UA
  - We don't make any guarantees for how long we will retain reports -- e.g. user clears their settings/cookies and we _have_ to purge the reports
  - We may drop the report after one retry, or after multiple
  - We may even disable report delivery in some cases

Personally, I don't think we should make *any* promises about lifetime of the report, and developers should not assume that they'll get all of them.

**Comment by patrickkettner** [comment]
I would personally prefer `max-age` to not be required.

Its a great feature for power users, but not something that the average website would be that likely to care about. Just like `Cache-Control` headers are not a _requirement_ to serve http traffic, making this a requirement sort of feels like it would just cause a paradox of choice for a lot of folks.

**Comment by igrigorik** [comment]
Omitting cache-control only works because heuristic caching kicks in.. and that's a complicated mess that nobody understands. In this case, heuristic caching doesn't make sense (we have nothing to infer it from; we shouldn't tie it to the document), and I don't think we want to assume infinite lifetime either.

**Comment by patrickkettner** [comment]
why don't we want to tie it to the headers that came with the loaded document or asset that triggered the report?

**Comment by igrigorik** [comment]
Because the lifetime of the document has nothing to do with the lifetime of the reporting endpoint.. A large number of HTML documents are no-cache or ttl=0 (dynamic content), whereas I want my reporting endpoint to be cached for at least 24hrs to catch (failed) repeat navigations.

**Comment by patrickkettner** [comment]
thats a great reason to have the ability to specify max-age headers, not necessarily one to require them, right?

**Comment by igrigorik** [comment]
Heuristic caching is bust. I'd much prefer we explicitly require developers to think through this, instead of scratching their heads later as to how and why their reports are not being delivered... heuristic caching of no-cache is.. no-cache. The reporting endpoint is only active for while the page is open.

**Comment by juliatuttle** [comment]
+1 to let's not specify a default. Implementing "reporting endpoint only active while the page is open" would be a nightmare.

**Comment by RByers** [comment]
I'm OK leaving `max-age` as required for now.  We can always compatibly revisit this later if needed.  @patrickkettner WDYT?

**Comment by patrickkettner** [comment]
I'd still rather have it be non-required, but it is not a blocker for me

**Comment by patrickkettner** [comment]
as I was the only blocker, closing as wontfix
