### ISSUE TITLE
Add priority field to endpoint tuple and client

### ISSUE THREAD

**Issue by juliatuttle** [WICG/reporting#39]
I think it would make sense for endpoint tuples (and therefore clients) to have an optional "priority" field, defaulting to zero, that causes the user agent to prefer higher-priority (lower-numbered, unless that's too confusing) endpoints first. This would let site owners configure fallback endpoint(s), instead of only being able to use multiple endpoints for load balancing.

**Comment by patrickkettner** [comment]
I know its been a while since this was opened, but I believe this is essentially supported now. You can include multiple endpoints within the same `group`, and the UA will fallback through the group based on source order (i.e. index 0 first, index 1 second, etc) - right?

@RByers @juliatuttle

**Comment by juliatuttle** [comment]
No, there's no ordering, and my code in Chromium currently deliberately picks one at random to avoid accidentally providing an ordering.

I'd also suggest we add a "weight" field, for load-balancing among endpoints at a single priority level. (An example combination of this would be: specify a high-priority main endpoint with weight 99, specify a high-priority canary endpoint with weight 1, and specify a lower-priority fallback endpoint with weight 100. Weights in a given priority need not add up to 100, though.)

**Comment by dcreager** [comment]
Closed in #70
