### ISSUE TITLE
The report having a property named `report` is confusing

### ISSUE THREAD

**Issue by RByers** [WICG/reporting#42]
This is a silly thing but it's been bugging me.  Mostly the spec uses the term [report](http://wicg.github.io/reporting/#report) to refer to the larger thing (eg. that has a `type`) and [body](http://wicg.github.io/reporting/#dom-report-body) to refer to the the type-specific data structure.  But then the [exposed property name for the body is "report"](http://wicg.github.io/reporting/#try-delivery).

This leads to awkward observer [code](https://github.com/WICG/reporting/blob/master/EXPLAINER.md#reportingobserver---observing-reports-from-javascript) like `report.report`.

Can we just rename the property to `body` to match the spec terminology?

Alternately, since we likely want a WebIDL definition for each report type (at least those exposed via #29), we could recast the spec in terms of those types instead of a generic notion of "any objection which can be serialized to JSON" (which itself is [problematic](https://github.com/w3c/browser-payment-api/issues/307)), and then the body could just be contained directly in the report via interface inheritance:

```webidl
interface ReportBase
{
    readonly attribute string type;
};

interface DeprecationReport : ReportBase
{
    readonly attribute string message;
};
```

@mikewest @juliatuttle

**Comment by mikewest** [comment]
Renaming the property to `body` sounds perfectly fine to me. I think I like that clear separation between the generic reporting API stuff, and the stuff specific to a specific thing that's being reported. It also resolves the question that will inevitably crop up when a feature has a property that collides with a generic reporting API property (e.g. assume your example had deprecation "types").
