### ISSUE TITLE
Should any Report-To header clear unspecified endpoints?

### ISSUE THREAD

**Issue by juliatuttle** [WICG/reporting#48]
When an origin sends a Report-To header, right now, we simply add/update/remove whatever endpoints are specified in it; any that aren't specified remain in place.

It seems to me that it might be more useful to *replace* the set of active endpoints with the ones specified in the header, since otherwise origins have to keep track of every endpoint they've specified and explicitly clear them later.

Do we have any other specs that allow multiple configuration tuples or such that we can reference for consistency? HSTS only has a flat config, so max-age=0 effectively clears the entire config.

**Comment by igrigorik** [comment]
> It seems to me that it might be more useful to replace the set of active endpoints with the ones specified in the header, since otherwise origins have to keep track of every endpoint they've specified and explicitly clear them later.

Agreed. Practically speaking, it would be impossible for an origin to know and garbage collect all the different origins different responses might register otherwise. We should treat the policy as a wholesale replacement of previous registrations, with max-age=0 mapping to "please erase whatever you had before".

**Comment by juliatuttle** [comment]
Actually, a thought: What's the point of specifying an endpoint with max-age=0 if you could just not specify it at all? And if you don't want *any* endpoints, you can just say "Report-To: " with an empty value, right?

**Comment by dcreager** [comment]
As of #67 the logic is now that the contents of a header completely replace all of the endpoints that were previously in the cache for the origin.

It's still possible to say `max-age=0`, but as Julia points out, that's not needed anymore since you can just leave that endpoint out completely.  Any objections to requiring `max-age > 0` as a result?

**Comment by igrigorik** [comment]
> And if you don't want any endpoints, you can just say "Report-To: " with an empty value, right?

In theory, yes, but in practice this feels a little odd to me. I wouldn't be surprised if some frameworks / proxies / servers would collapse and eliminate such values before emitting them?

**Comment by dcreager** [comment]
> would collapse and eliminate such values before emitting them

Ah, yuck, you're right!  So we need some explicit non-empty `Report-To` value which means "I actively assert I want to have no endpoint groups".  As currently written, you'd need something like

``` http
Report-To: {"group": "none", "max-age": 0, "endpoints": [{"url": "https://example.com/a-valid-url"}]}
```

That's a bit verbose; if we relaxed some of the integrity constraints we could get that down to


``` http
Report-To: {"group": "none"}
```

Is that a problem worth solving?

**Comment by igrigorik** [comment]
But then you still have to support the former, for cases where you want to remove one of multiple endpoints — right? FWIW, I'd keep it simple.. and verbose for now?

**Comment by dcreager** [comment]
Agreed re your conclusion :smile: 

`max-age` is a feature of a group now, not of individual endpoints.  So if you want to remove an endpoint from a group, you just leave it out of the `endpoints` array when you send out a new value for the header.

**Comment by dcreager** [comment]
Consensus is to leave this as-is
