### ISSUE TITLE
Friendly TAG Review: UA string consistency

### ISSUE THREAD

**Issue by travisleithead** [WICG/reporting#52]
In response to https://github.com/w3ctag/design-reviews/issues/195

* Buffered reports (or time-delayed), UA might not match at that later time that they're set. UA String at the moment the event occurred should be recorded in the report.

**Comment by RByers** [comment]
Oooh, good point. Thanks.

I can totally see the need for this in the HTTP case.  The most common case in Chrome is issues hit only when viewing a page on Android with "request desktop site".

I'm less sure about the ReportingObserver case.  I think the only way the report-generating UA could be different from `navigator.userAgent` is if a developer had changed it in between (eg. using debugger tools), in which case all bets are probably off (the page isn't going to be designed to handle the UA string changing in the middle anyway).  Of course if we add it to the HTTP request, we could add it to the JS API for consistency anyway.

@mikewest WDYT?

**Comment by mikewest** [comment]
Sounds reasonable. If we capture the UA for the HTTP report, we'll automatically have it for the observer case as well (though I agree with Rick that it's unlikely that there would be differences in the visible string between the trigger and the observed data).

**Comment by RByers** [comment]
> If we capture the UA for the HTTP report, we'll automatically have it for the observer case as well

I don't think that's necessarily true.  The way I've defined it [at the moment](https://github.com/WICG/reporting/pull/47), we don't have `age` or `url` in the `ReportingObserver` case either (since `age` is meaningful only for HTTP reporting, and `url` is, like `userAgent`, superfluous).
