### ISSUE TITLE
Group clients by origin, not endpoint

### ISSUE THREAD

**Issue by juliatuttle** [WICG/reporting#64]
I've got a couple of spec changes (add priority/weight to endpoints, remove existing endpoints that are not listed in a newly-processed header) queued, and both of them would be much easier to implement if we organized clients by origin, not by endpoint. Practically, in my code, I've never wanted to inspect all of the clients of an endpoint, but I frequently want to inspect all of the endpoints of an origin.

I'm planning to reorganize this unless there's some opposition. Thoughts?

**Comment by RByers** [comment]
@dcreager can we close this issue now?

**Comment by dcreager** [comment]
Yep!

**Comment by dcreager** [comment]
Closed by #67
