### ISSUE TITLE
Scope of includeSubdomains

### ISSUE THREAD

**Issue by dcreager** [WICG/reporting#66]
Right now you can specify a different value of `includeSubdomains` for each endpoint in an origin's `Report-To` header.  Do we have a use case for that?  It seems like that flag should apply to the origin as a whole, and not to individual endpoints.  That would simplify the logic for choosing which endpoints are eligible for a particular report.

**Comment by juliatuttle** [comment]
Good question! There's no reason it couldn't be implemented per-origin instead, and that would indeed simplify things. It would require adding a layer of config, though; right now the header is just an (implied) array of dictionaries, one per endpoint. We'd have to do something like `{"endpoints":[`_existing header_`],"include-subdomains":true}`.

**Comment by dcreager** [comment]
Yeah, the header change threw me for a loop too.  We could make this per-group, instead of per-origin, and keep the same header format.  A group would have "include-subdomains" true if *all* of the endpoints with that group have it set to true.

**Comment by juliatuttle** [comment]
Hrm, that sounds kind of messy. It does make sense to do it on a per-group
basis, I think, since groups will often map to features, which individually
may or may not want wildcard behavior.

**Comment by dcreager** [comment]
Yeah I like per-group better than per-origin, but the parsing nonsense was only an attempt to not change the header format.

**Comment by juliatuttle** [comment]
...you know, I've got an even better idea. What if the header were an array
of groups, and we moved both include-subdomains and max-age to the group
level? We're using JSON field values, which basically implies an array
around the normalized header value, so Foo: A and Foo: B will parse as
[A,B].

This would look like:

Report-To: {"group": "network-errors", "max-age": 86400,
"include-subdomains": true, "endpoints": [{"url": "nel1.example.com",
"priority": 1, "weight": 1}, {"url": "nel2.example.com", "priority": 2,
"weight": 1}]}

That's... kind of a mouthful, but might work?

**Comment by dcreager** [comment]
If changing the header format is an option, then I like your suggestion a lot.

**Comment by juliatuttle** [comment]
It's work, but it's doable -- AFAIK nobody has shipped this yet.

**Comment by igrigorik** [comment]
> Right now you can specify a different value of includeSubdomains for each endpoint in an origin's Report-To header. Do we have a use case for that? It seems like that flag should apply to the origin as a whole, and not to individual endpoints.

Agreed, that makes sense.

> Report-To: {"group": "network-errors", "max-age": 86400,
> "include-subdomains": true, "endpoints": [{"url": "nel1.example.com",
> "priority": 1, "weight": 1}, {"url": "nel2.example.com", "priority": 2,
> "weight": 1}]}

👍 

Above example snuck in priority+weight which are undefined today, but that's a separate discussion.

**Comment by dcreager** [comment]
> Above example snuck in priority+weight which are undefined today, but that's a separate discussion.

Yup, we have #39 open to track that.  I have a [draft patch](/dcreager/reporting/commit/76285e5a1b0d7bc34730e7ab545ff0ac1e96b710) that adds that to the spec, haven't opened a PR for it yet since it depends on #67.

**Comment by dcreager** [comment]
Closed by #67
