### ISSUE TITLE
General Questions with this project

### ISSUE THREAD

**Issue by ayumihamsaki** [WICG/reporting#69]
Hi,

Got a few questions with regards to this api using with csp. I know no browser is using it yet.

1. Would this be correct code to add into php:

`report-to { 'url': 'https://report-uri.io/r/default/csp/reportOnly', 'group': 'csp-endpoint', 'max-age': 10886400 }`

2. Backwards compatibility would this be correct:

`Content-Security-Policy: ...; report-uri 'https://report-uri.io/r/default/csp/reportOnly'; report-to { 'url': 'https://report-uri.io/r/default/csp/reportOnly', 'group': 'csp-endpoint', 'max-age': 10886400 }`

3. Are there any working testing tools out there that accept report-to?

4. When would be a rough date for a lauch of this api into Google Canary?

5. Is there a Chrome experiments for this as well in Google Canary I can turn on?

~ I know this is still in early stages, but I use CSP a lot and just want to know for future records etc.

Thanks.

**Comment by juliatuttle** [comment]
1. No, you have to specify a HTTP header with `Report-To` as the name and your JSON there as the value.
2. No, you'd want to specify `report-to 'csp-endpoint'` -- the report-to field in the CSP header specifies a Reporting endpoint group. (I'm not exactly sure on the quoting; I've never worked with CSP headers myself.)
3. Not as far as I know.
4. It's already silently running in Chromium canary and dev for some users, but we don't have a formal launch date set yet.
5. Yes, you can turn it on by forcing the `ReportingAPI` and `NetworkErrorLogging` experiments on using `--enable-features`.

**Comment by ayumihamsaki** [comment]
Thank you
