### ISSUE TITLE
Revert "3P anonymization"

### ISSUE THREAD

**Issue by igrigorik** [WICG/reporting#81]
> Note: The intended use case for allowing reports to be sent to a different
> endpoint is so that reports containing sensitive information (either for
>  security or privacy reasons) can be aggregated and anonymized at a third party..

Per discussion in https://github.com/WICG/reporting/pull/75#discussion_r188963937, I propose we revert this text and work on UA logic to perform aggregation + provide strong guidance for anonymization requirements before any data leaves the client.

**Comment by juliatuttle** [comment]
+1

**Comment by paulmeyer90** [comment]
Being reverted here: #84
